### ISSUE TITLE
Event sorting by date

### ISSUE THREAD

**Issue by hepplerj** [endangereddataweek/endangereddataweek.org#6]
Events aren't sorting by date in the Maps/Events view.

**Comment by hepplerj** [comment]
Just noticed you added sorting to the event table, that's awesome! Should we set the default sort to be by date?

**Comment by waynegraham** [comment]
So right now they're "sorted" by when they are input in to the spreadsheet. Right now since they both happen on the same time string (we should test other dates) the sorting doesn't do anything as it wouldn't affect the order.

Make sense? 

Also, I didn't make much use of the JS plugin for this (https://www.dynatable.com). There are lots of possibilities for sorting/querying.

**Comment by hepplerj** [comment]
Gotcha. I added an event that takes place a couple days before those already in the spreadsheet, which led met to notice they weren't sorting.
